### ISSUE TITLE
keybinding

### ISSUE THREAD

**Issue by Vincentzc** [leftstick/vscode-favorites#11]
i think it's a good idea to have hot key to add to favorites and remove from it when i editing a file,therefore i don't have to use my mouse to find where my file is and right click and ...
i have tried to set keybinding ,but it just not work.
think about it and thanks!

**Comment by leftstick** [comment]
Nice catch, now with `1.4.0`, add/delete assets is available in activeEditor, which means you can bind any hot key you like for the function
