### ISSUE TITLE
Error message when no workspace is loaded

### ISSUE THREAD

**Issue by roarjoss** [leftstick/vscode-favorites#15]
Hello,

I get error message when trying to use Favorites.
Is it possible that Favorites could write to user settings if no workspace is loaded?

Best regards,
Roar Jøssund

![favorites-error-message](https://user-images.githubusercontent.com/15902764/42017889-c3b4a4fa-7ab0-11e8-8f39-7bb7e4cc83ee.png)

**Comment by leftstick** [comment]
sorry for the late response. It is hard to support such case by current design. So I will close it for now
