### ISSUE TITLE
Enable Single/Double Click Open Mode

### ISSUE THREAD

**Issue by EigenTheory** [leftstick/vscode-favorites#17]
With the default setting of "workbench.list.openMode": "singleClick", double clicking on items in the `Favorites` does not open the file, but opens the file in preview mode.

**Comment by fabiospampinato** [comment]
Unfortunately I think there's no API for detecting double clicks on tree items.

**Comment by sguillia** [comment]
A double-click on a favourite file should open it in Keep Open mode.

Should we make a feature request to VS Code upstream?

**Comment by leftstick** [comment]
It was requested for a while [27823](https://github.com/Microsoft/vscode/issues/27823), but seems no updates

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/39601#issuecomment-376415352 suggests a possible workaround.
