### ISSUE TITLE
Reveal in explorer option

### ISSUE THREAD

**Issue by leokruk** [leftstick/vscode-favorites#18]
Would be nice to expand functionality with add reveal in explorer right click option.

**Comment by Daijobou** [comment]
Yes, I missing "Search in folders" or "compare" too. ;)

**Comment by gjsjohnmurray** [comment]
'Reveal in Finder' is already implemented, and my recently-merged PR #32 gives this the correct platform-specific text (e.g. 'Reveal in File Explorer' when on Windows).

I plan to submit a PR that will implement 'Reveal in Side Bar' (see https://github.com/leftstick/vscode-favorites/issues/19#issuecomment-626693786)
