### ISSUE TITLE
feature request: right-click "reveal in side bar/explorer"

### ISSUE THREAD

**Issue by Gettyk** [leftstick/vscode-favorites#19]
Thanks for you great extension!

That would be great if we could right click on a file in the 'favorite section' and select reveal in side-bar or reveal in explorer.

**Comment by leftstick** [comment]
nice feature, i will think about it. Or it would be good if you give me a pr for it

**Comment by Daijobou** [comment]
Dublicate? https://github.com/leftstick/vscode-favorites/issues/18

**Comment by irvnriir** [comment]
[Explorer RMB functions]
all VSC's Explorer RMB actions should be accessible from it https://github.com/leftstick/vscode-favorites/issues/18 , but instead of merging them with the sorting controls, its better to just add the Tab RMB 's "Reveal in Side Bar" function .

**Comment by leftstick** [comment]
@geforcesong do you like to take a look at it?

**Comment by SashaOv** [comment]
The motivation is that there are some commands (like copy/paste) that this extension doesn't implement so switching to the explorer will be useful to be able to run these commands. Thanks for your consideration.

**Comment by geforcesong** [comment]
fixed, will be released soon

**Comment by irvnriir** [comment]
PLEASE add the Reveal In Sidebar action, for functions inside the VSC, like comparison tools and other .

**Comment by gjsjohnmurray** [comment]
> PLEASE add the Reveal In Sidebar action, for getting to the RMB menu with functions inside the VSC, like comparison tools and other .

I plan to submit a PR for this after my existing PR #26 has been merged.
