### ISSUE TITLE
Icon Support?

### ISSUE THREAD

**Issue by donaldguy** [leftstick/vscode-favorites#2]
I see in your gif that you, like me, have an icon theme in your main explorer window

I haven't done any vscode extension development, so I have no idea how hard an ask it is to interact with other extensions... but

it would be cool if icons were also shown in the favorites window

**Comment by leftstick** [comment]
Sure, i have the same question. Unfortunately, `vsocde` engine doesn't provide such ability for extensions. 

But good news is the team is working on that, we can track the process at [Enhance custom tree views](https://github.com/Microsoft/vscode/issues/27823).

Once the `vscode` team finish those APIs, i will bring it into this extension asap.

Thanks for asking a great feature, i will keep this issue open for anyone who's looking forward this feature

**Comment by leftstick** [comment]
Icon is now supported

![screen shot 2018-02-26 at 10 18 11 am](https://user-images.githubusercontent.com/1059956/36650423-5fc10efc-1ade-11e8-8096-feb44a83a38f.png)
