### ISSUE TITLE
Doesn't work with remote

### ISSUE THREAD

**Issue by anarelion** [leftstick/vscode-favorites#23]
Go to a remote folder, right click and then Add to Favourites.
Nothing happens.

**Comment by gjsjohnmurray** [comment]
@anarelion what kind of remote folder? Maybe you are using an extension such as Remote Workspace (mkloubert.vscode-remote-workspace) or Remote FS (liximomo.remotefs)? If so, you might be interested in an enhancement that I am considering submitting as a PR.
