### ISSUE TITLE
Open file in new tab

### ISSUE THREAD

**Issue by kdcro101** [leftstick/vscode-favorites#3]
Implement ability to open selected (clicked) file in new tab. 
Now every file doubleclicked replace file before.

Thanks

**Comment by leftstick** [comment]
You mean if a resource opened before, when you click it from `favorites`, you want this resource opened in a new tab, not the previous one?

**Comment by kdomagoj** [comment]
Sorry for late reply,
Yes. If I open file1.ext and I want to open file2.ext, currently it replaces file1.ext and not opening new tab. 
This extension is time saver if it would have only this functionality added. 
I have uninstall it because I was always in single tab. I'vew tried double-click, ctrl+double-click...

Thanks for reply!
Domagoj

**Comment by leftstick** [comment]
@kdcro101  since vscode extension API only support select function(which is click) for now. So i improved in this way:

If you have `"workbench.editor.enablePreview": false` in your settings, the file will be opened in new tab

**Comment by kdcro101** [comment]
Thanks a lot!

I see you've added icons! great! This extension significantly increases productivity!
` "workbench.editor.enablePreview": false` works perfectly.

One "litle" thing: please sort directories first and then files as is practice in IDEs.

![favorites](https://user-images.githubusercontent.com/23455652/37546163-e2dfae2e-296b-11e8-9f95-a754e8aaf7a1.jpg)

Here you can see  in my case.

P.S.  Update animation of your extension front page on Visual Studio Market place so people can see icon support which is great helper for focusing

**Comment by leftstick** [comment]
@kdcro101 new sort function released, please try it again

**Comment by kdcro101** [comment]
@leftstick, thank you for quick reply!

I've reinstalled extension to version 1.3.1

When I add directory to favorites its contents are still ordered by file name only.

![favorites1](https://user-images.githubusercontent.com/23455652/37565902-064ab13c-2ab2-11e8-84a9-c30d82577a7d.jpg)

Here you can directory "test" added to favorites. Its contents are still sorted old way.

I've added  "favorites.sortOrder": "ASC" //DESC to settings.

Can you add context menu ( right click) from file explorer when clicked on favorite item (and descendants)?
That would be a production booster!

Thanks a lot!

**Comment by leftstick** [comment]
@kdcro101  `1.3.2` is released, please have a try
