### ISSUE TITLE
Not Update When add / delete file.

### ISSUE THREAD

**Issue by flame4** [leftstick/vscode-favorites#33]
hi, when i create a new file / delete some file, the folder on the favorites will not update, instead it will keep old view.

And, file operation (rename, create, etc) seems forbiding in favorites tab.

i wonder whether this is a known problem, or something i can do to fix it.

thx. :)

**Comment by gjsjohnmurray** [comment]
I plan to submit a PR that will add a Refresh button to the header of the Favorites view here:

![image](https://user-images.githubusercontent.com/6726799/81567021-a1aa7580-9393-11ea-94bb-8867c643c7ed.png)

Until then a workaround is to use the button that changes the sort order. But beware that if you currently use MANUAL sort order, clicking that button will switch you to ASC or DESC order. To reinstate MANUAL order:

![image](https://user-images.githubusercontent.com/6726799/81566838-598b5300-9393-11ea-8d0a-5428580fa5cb.png)

Or edit your .code-workspace file directly.

**Comment by flame4** [comment]
thx, that's very helpful.   :)

i thought this issue should be closed when this pr is merged, so i'll keep it open.
thanks for your job again~
