### ISSUE TITLE
Can't add new favorites

### ISSUE THREAD

**Issue by sergey-beloglazov** [leftstick/vscode-favorites#45]
I can't add a new favorite to existing. It might started after adding separate .code-workspace file to the project dir.
In other projects it works fine.
In the project with .code-workspace I can't neither add nor delete.

**Comment by leftstick** [comment]
@geforcesong would you like to take a look?

**Comment by sergey-beloglazov** [comment]
I found a problem source and fix it.
My .code-workspace was incorrect ("missed {").
So it can read it, but can't modify.
Thank you!
