### ISSUE TITLE
no "Add to Favorites" menu in context menu of explorer

### ISSUE THREAD

**Issue by YohanHale** [leftstick/vscode-favorites#48]
after install (and restart vscode), there is no "Add to Favorites" menu in **context menu of explorer**.
There is such a menu in **context menu of editor** but not work

**Comment by leftstick** [comment]
@YohanHale  can you describe more about your issue? I cannot reproduce it

**Comment by YohanHale** [comment]
![QQ截图20201109153424](https://user-images.githubusercontent.com/31202046/98512341-2291ed80-22a1-11eb-8e21-b06c95dd0d50.png)
I googled but found no similar issue, may not be a bug. Can it be solved?

**Comment by leftstick** [comment]
`Add to Favorites` will not be added to `OPEN EDITORS`. 

You have to open a folder via vscode, and `Add to Favorites` will be added to folder explorer
