### ISSUE TITLE
Support multiple root folder of workspace

### ISSUE THREAD

**Issue by moon6pence** [leftstick/vscode-favorites#5]
Recently, VSCode supports adding multiple root folders to workspace. 

However, It seems that I cannot add favorite file which is not in "first" root folder in workspace with vscode-favorites addon. 

Additionally, it would be nice if I can add favorite file even not in any root folders in workspace, by right-click  file on OPEN EDITORS list on Side bar or right-click filename on tab bar.

**Comment by leftstick** [comment]
@moon6pence 

for the first issue, it is fixed in `1.1.6`.

I need to think about more scenarios, maybe provide it in next release
