### ISSUE TITLE
Option to store favorites somewhere other than .vscode/settings.json

### ISSUE THREAD

**Issue by dlong500** [leftstick/vscode-favorites#6]
I commit my `settings.json` file in my git repo, so storing transient favorites in that file will cause problems with that file frequently changing.  Ideally there should be another place to store the favorites data.  I would think most people wouldn't want to commit favorites in source control.  Unfortunately as it stands now I can't use this extension because of that issue.

**Comment by tschofen** [comment]
+1

**Comment by leftstick** [comment]
Supported in `1.2.0`
