### ISSUE TITLE
Enable full path Display

### ISSUE THREAD

**Issue by Eun** [leftstick/vscode-favorites#7]
It would be great to have an option the display of the full path.

And maybe even the option to display it relative to the workspace path.

**Comment by leftstick** [comment]
Can you give my some examples? I am not sure i understand your point by "display of the full path"

**Comment by Eun** [comment]
If you have multiple files sharing the same name it gets hard to identify the correct file.
Maybe this screenshot makes it clearer:
![screenshot from 2018-01-25 14-26-13](https://user-images.githubusercontent.com/796084/35390495-fcbe3958-01db-11e8-92bd-e39eee6ebebe.png)

**Comment by leftstick** [comment]
Got it. @Eun , so do you have any suggestion? What shall we design for this purpose?

**Comment by leftstick** [comment]
Once hovering on the item, path should be shown now, is this enough for you?

**Comment by tatoosh** [comment]
I have the same problem.
In my szenario i have a git project with folders for livesystem and testsystem.
i can't see in the favorites if the files (file name is of course the same in both systems) is stores from live or testsystem.

My suggestion is to show the root folder of the file in grey oder with a pipe to the right of the file:

![grafik](https://user-images.githubusercontent.com/3670907/37524636-b5a54e78-292a-11e8-816b-028428174aea.png)

**Comment by leftstick** [comment]
I tried with `tooltip` as following, is it ok for your case?

![2018-03-17 6 37 48](https://user-images.githubusercontent.com/1059956/37554384-79568e94-2a12-11e8-9029-0908c694ab85.png)
![2018-03-17 6 38 18](https://user-images.githubusercontent.com/1059956/37554386-7aca0404-2a12-11e8-874f-a125f5bf61c7.png)

**Comment by leftstick** [comment]
@tatoosh sure, it is included in `1.3.1`

**Comment by tatoosh** [comment]
Cool thx

Howard.Zuo <notifications@github.com> schrieb am Sa., 17. März 2018, 13:33:

**Comment by jeffabailey** [comment]
I don't see a path in the tooltip.

Do I need to enable it?

<img width="696" alt="image" src="https://user-images.githubusercontent.com/776901/223905107-f8e6e01d-b66e-4e50-9ae1-6fab4b8f1025.png">

**Comment by leftstick** [comment]
@jeffabailey  i remember it should be the path relative to your root workspace. Not the absolute path. 
So the `README.md` file should be in your root folder, that's why you see it without any "path" before the filename
