### ISSUE TITLE
Grouping favorites in folders

### ISSUE THREAD

**Issue by pipa** [leftstick/vscode-favorites#8]
Would be nice to group files in the favorites side-bar

**Comment by fabiospampinato** [comment]
This would be great.

**Comment by shengyongjiang** [comment]
virtual sub folder is really useful

**Comment by joseorihuela** [comment]
+1 on this!

**Comment by studgeek** [comment]
Favorites folders seems to be the biggest gap versus https://marketplace.visualstudio.com/items?itemName=kdcro101.favorites.

**Comment by GitMensch** [comment]
Isn't this what was implemented with https://github.com/leftstick/vscode-favorites/pull/58 ? If yes then this should be closed, if not please explain the differences.

**Comment by leftstick** [comment]
@GitMensch  you are right, it has been supported. This issue should be closed
